In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
a = np.arange(15).reshape(3, 5)
print(a.shape)

(3, 5)


In [9]:
#the number of axes (dimensions) of the array
a = np.arange(15).reshape(3, 5)
print(a.ndim)

2


In [10]:
a = np.arange(15).reshape(3, 5)
print(a.dtype.name)

int32


In [12]:
#the total number of elements of the array
a = np.arange(15).reshape(3, 5)
print(a.size)

15


In [13]:
np.zeros ((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones( (2,3,4), dtype=np.int32 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [29]:
#To create sequences of numbers
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [10]:
np.arange( 0, 2, 0.3 )

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [14]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.random.random((2,3))

array([[0.35629198, 0.66557848, 0.18855673],
       [0.13644471, 0.72537835, 0.58267408]])

In [17]:
from numpy import pi
np.linspace( 0, 99, 100 )

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [13]:
np.sin(np.linspace( 0, 2*pi, 100 ))

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [23]:
#the product operator * operates elementwise in NumPy arrays
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
#print a 
#print b
#b
# shape相同的情况下，ndarray是对应元素加减
c = a-b
print(c)
print('----------')
# 如果ndarray加减一个数，则为每个元素对应加减这个数
d = a - 1
print(d)
print('----------')
# 乘方同理
print(b**2)


[20 29 38 47]
----------
[19 29 39 49]
----------
[0 1 4 9]


In [25]:
#The matrix product can be performed using the dot function or method
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
print(A)
print(B)
print('----------')
# 对应元素乘
print(A*B)
print('----------')
# 矩阵相乘，两种方法
print(A.dot(B))
print(np.dot(A, B) )

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
----------
[[2 0]
 [0 4]]
----------
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
