In [2]:
import numpy as np
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [3]:
#Return the floor of the input
a = np.floor(10*np.random.random((3,4)))
print(a)
print('---------------')
print(a.shape)
print('---------------')
# flatten the array
print(a.ravel())
a.shape = (6, 2)
print(a)
print(a.T)
print(a.resize((2,6)))

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
a.reshape(3,-1)

[[8. 9. 4. 8.]
 [6. 8. 1. 6.]
 [1. 6. 7. 0.]]
---------------
(3, 4)
---------------
[8. 9. 4. 8. 6. 8. 1. 6. 1. 6. 7. 0.]
[[8. 9.]
 [4. 8.]
 [6. 8.]
 [1. 6.]
 [1. 6.]
 [7. 0.]]
[[8. 4. 6. 1. 1. 7.]
 [9. 8. 8. 6. 6. 0.]]
None
[[8. 9. 4. 8. 6. 8.]
 [1. 6. 1. 6. 7. 0.]]


array([[8., 9., 4., 8.],
       [6., 8., 1., 6.],
       [1., 6., 7., 0.]])

In [6]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print('-----')
print(b)
print('-----')
# 水平拼接
print(np.hstack((a,b)))
print('-----')
# 垂直拼接
print(np.vstack((a,b)))


#np.hstack((a,b))

[[3. 0.]
 [5. 9.]]
-----
[[8. 3.]
 [3. 5.]]
-----
[[3. 0. 8. 3.]
 [5. 9. 3. 5.]]
-----
[[3. 0.]
 [5. 9.]
 [8. 3.]
 [3. 5.]]


In [7]:
a = np.floor(10*np.random.random((2,12)))
print(a)
print(np.hsplit(a,3))
print(np.hsplit(a,(3,4)))   # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print(a)
print(np.vsplit(a,3))

[[1. 3. 8. 4. 5. 8. 8. 8. 8. 8. 2. 2.]
 [2. 3. 8. 9. 8. 7. 3. 4. 0. 4. 3. 4.]]
[array([[1., 3., 8., 4.],
       [2., 3., 8., 9.]]), array([[5., 8., 8., 8.],
       [8., 7., 3., 4.]]), array([[8., 8., 2., 2.],
       [0., 4., 3., 4.]])]
[array([[1., 3., 8.],
       [2., 3., 8.]]), array([[4.],
       [9.]]), array([[5., 8., 8., 8., 8., 8., 2., 2.],
       [8., 7., 3., 4., 0., 4., 3., 4.]])]
[[5. 3.]
 [3. 3.]
 [1. 0.]
 [5. 3.]
 [6. 6.]
 [0. 9.]
 [9. 5.]
 [6. 4.]
 [1. 6.]
 [4. 4.]
 [9. 4.]
 [4. 2.]]
[array([[5., 3.],
       [3., 3.],
       [1., 0.],
       [5., 3.]]), array([[6., 6.],
       [0., 9.],
       [9., 5.],
       [6., 4.]]), array([[1., 6.],
       [4., 4.],
       [9., 4.],
       [4., 2.]])]


In [13]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
print(b is a)
b.shape = (3,4)
print(a.shape)
print(id(a))
print(id(b))

True
(3, 4)
2239129219120
2239129219120


In [15]:
#The view method creates a new array object that looks at the same data.
c = a.view()
print(c is a)
c.shape = 2,6
print(a.shape)
c[0,4] = 1234
print(a)
print(id(a))
print(id(c))

False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
2239129219120
2239129219920


In [16]:
#The copy method makes a complete copy of the array and its data.
d = a.copy() 
print(d is a)
d[0,0] = 9999
print(d)
print(a)

False
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
